CREATE DATABASE IF NOT EXISTS Examen_Final_Dwes;
USE Examen_Final_Dwes;

CREATE TABLE IF NOT EXISTS users(
id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
email VARCHAR(255) NOT NULL UNIQUE,
password_user TEXT NOT NULL,
user_name VARCHAR(255) NOT NULL,
rol VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS favoritos(
id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
id_personaje INT UNSIGNED NOT NULL,
id_user INT UNSIGNED NOT NULL,
img_personaje TEXT,
description_personaje TEXT,
CONSTRAINT fk_favoritos_usuarios
FOREIGN KEY (id_user)
REFERENCES users(id)
ON DELETE CASCADE
ON UPDATE CASCADE
);